/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockProperty__factory } from './MockProperty__factory.js';
export { MockUSDC__factory } from './MockUSDC__factory.js';