/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as trancheTokensSol from './TrancheTokens.sol/index.js';
export { InterestDistributor__factory } from './InterestDistributor__factory.js';
export { LendingPool__factory } from './LendingPool__factory.js';
export { SecondaryMarket__factory } from './SecondaryMarket__factory.js';