/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as trancheTokensSol from './TrancheTokens.sol/index.js';
export type { trancheTokensSol };
export type { InterestDistributor } from './InterestDistributor.js';
export type { LendingPool } from './LendingPool.js';
export type { SecondaryMarket } from './SecondaryMarket.js';