/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ILendingPool {
      
    export type LoanStruct = {borrower: AddressLike, amount: BigNumberish, interestRate: BigNumberish, ltv: BigNumberish, startTime: BigNumberish, endTime: BigNumberish, propertyValue: BigNumberish, propertyId: BytesLike, status: BigNumberish}

    export type LoanStructOutput = [borrower: string, amount: bigint, interestRate: bigint, ltv: bigint, startTime: bigint, endTime: bigint, propertyValue: bigint, propertyId: string, status: bigint] & {borrower: string, amount: bigint, interestRate: bigint, ltv: bigint, startTime: bigint, endTime: bigint, propertyValue: bigint, propertyId: string, status: bigint }
  
    }

  export interface LendingPoolInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_ROLE" | "DEFAULT_ADMIN_ROLE" | "JUNIOR_RATIO" | "MAX_LTV" | "MIN_DEPOSIT" | "OPERATOR_ROLE" | "PERCENTAGE_DIVISOR" | "SENIOR_RATIO" | "applyForLoan" | "deposit" | "getJuniorTVL" | "getLoan" | "getRoleAdmin" | "getSeniorTVL" | "getTotalValue" | "getTrancheRatio" | "getUserBalance" | "grantRole" | "hasRole" | "interestDistributor" | "juniorShares" | "juniorToken" | "liquidateLoan" | "loans" | "nextLoanId" | "renounceRole" | "repayLoan" | "revokeRole" | "seniorShares" | "seniorToken" | "setInterestDistributor" | "setTrancheTokens" | "supportsInterface" | "totalDeployed" | "totalJuniorDeposits" | "totalSeniorDeposits" | "usdc" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposited" | "InterestDistributed" | "LoanDefaulted" | "LoanOriginated" | "LoanRepaid" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'JUNIOR_RATIO', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_LTV', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_DEPOSIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'OPERATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PERCENTAGE_DIVISOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'SENIOR_RATIO', values?: undefined): string;
encodeFunctionData(functionFragment: 'applyForLoan', values: [BigNumberish, BytesLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'getJuniorTVL', values?: undefined): string;
encodeFunctionData(functionFragment: 'getLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSeniorTVL', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTotalValue', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTrancheRatio', values?: undefined): string;
encodeFunctionData(functionFragment: 'getUserBalance', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'interestDistributor', values?: undefined): string;
encodeFunctionData(functionFragment: 'juniorShares', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'juniorToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'liquidateLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'loans', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextLoanId', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'repayLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'seniorShares', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'seniorToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'setInterestDistributor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTrancheTokens', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalDeployed', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalJuniorDeposits', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSeniorDeposits', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'JUNIOR_RATIO', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_LTV', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_DEPOSIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'OPERATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PERCENTAGE_DIVISOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SENIOR_RATIO', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'applyForLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getJuniorTVL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSeniorTVL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTrancheRatio', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'interestDistributor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'juniorShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'juniorToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidateLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'loans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextLoanId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repayLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seniorShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seniorToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setInterestDistributor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTrancheTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDeployed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalJuniorDeposits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSeniorDeposits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace DepositedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish, isSenior: boolean, shares: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint, isSenior: boolean, shares: bigint];
      export interface OutputObject {user: string, amount: bigint, isSenior: boolean, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InterestDistributedEvent {
      export type InputTuple = [seniorAmount: BigNumberish, juniorAmount: BigNumberish];
      export type OutputTuple = [seniorAmount: bigint, juniorAmount: bigint];
      export interface OutputObject {seniorAmount: bigint, juniorAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanDefaultedEvent {
      export type InputTuple = [loanId: BigNumberish];
      export type OutputTuple = [loanId: bigint];
      export interface OutputObject {loanId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanOriginatedEvent {
      export type InputTuple = [loanId: BigNumberish, borrower: AddressLike, amount: BigNumberish, interestRate: BigNumberish];
      export type OutputTuple = [loanId: bigint, borrower: string, amount: bigint, interestRate: bigint];
      export interface OutputObject {loanId: bigint, borrower: string, amount: bigint, interestRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanRepaidEvent {
      export type InputTuple = [loanId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [loanId: bigint, amount: bigint];
      export interface OutputObject {loanId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish, isSenior: boolean, shares: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint, isSenior: boolean, shares: bigint];
      export interface OutputObject {user: string, amount: bigint, isSenior: boolean, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LendingPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): LendingPool;
    waitForDeployment(): Promise<this>;

    interface: LendingPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    JUNIOR_RATIO: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_LTV: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_DEPOSIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    OPERATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PERCENTAGE_DIVISOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SENIOR_RATIO: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    applyForLoan: TypedContractMethod<
      [amount: BigNumberish, propertyId: BytesLike, propertyValue: BigNumberish, term: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [amount: BigNumberish, isSenior: boolean, ],
      [bigint],
      'nonpayable'
    >
    

    
    getJuniorTVL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getLoan: TypedContractMethod<
      [loanId: BigNumberish, ],
      [ILendingPool.LoanStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSeniorTVL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTotalValue: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTrancheRatio: TypedContractMethod<
      [],
      [[bigint, bigint] & {senior: bigint, junior: bigint }],
      'view'
    >
    

    
    getUserBalance: TypedContractMethod<
      [user: AddressLike, isSenior: boolean, ],
      [bigint],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    interestDistributor: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    juniorShares: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    juniorToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    liquidateLoan: TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    loans: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, string, bigint] & {borrower: string, amount: bigint, interestRate: bigint, ltv: bigint, startTime: bigint, endTime: bigint, propertyValue: bigint, propertyId: string, status: bigint }],
      'view'
    >
    

    
    nextLoanId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    repayLoan: TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    seniorShares: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    seniorToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setInterestDistributor: TypedContractMethod<
      [_distributor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTrancheTokens: TypedContractMethod<
      [_seniorToken: AddressLike, _juniorToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    totalDeployed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalJuniorDeposits: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSeniorDeposits: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [shares: BigNumberish, isSenior: boolean, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'JUNIOR_RATIO'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_LTV'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_DEPOSIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'OPERATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PERCENTAGE_DIVISOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SENIOR_RATIO'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'applyForLoan'): TypedContractMethod<
      [amount: BigNumberish, propertyId: BytesLike, propertyValue: BigNumberish, term: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [amount: BigNumberish, isSenior: boolean, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getJuniorTVL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getLoan'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [ILendingPool.LoanStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSeniorTVL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalValue'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTrancheRatio'): TypedContractMethod<
      [],
      [[bigint, bigint] & {senior: bigint, junior: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getUserBalance'): TypedContractMethod<
      [user: AddressLike, isSenior: boolean, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'interestDistributor'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'juniorShares'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'juniorToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'liquidateLoan'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'loans'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, string, bigint] & {borrower: string, amount: bigint, interestRate: bigint, ltv: bigint, startTime: bigint, endTime: bigint, propertyValue: bigint, propertyId: string, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'nextLoanId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'repayLoan'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'seniorShares'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'seniorToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setInterestDistributor'): TypedContractMethod<
      [_distributor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTrancheTokens'): TypedContractMethod<
      [_seniorToken: AddressLike, _juniorToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalDeployed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalJuniorDeposits'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSeniorDeposits'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [shares: BigNumberish, isSenior: boolean, ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'InterestDistributed'): TypedContractEvent<InterestDistributedEvent.InputTuple, InterestDistributedEvent.OutputTuple, InterestDistributedEvent.OutputObject>;
getEvent(key: 'LoanDefaulted'): TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
getEvent(key: 'LoanOriginated'): TypedContractEvent<LoanOriginatedEvent.InputTuple, LoanOriginatedEvent.OutputTuple, LoanOriginatedEvent.OutputObject>;
getEvent(key: 'LoanRepaid'): TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'Deposited(address,uint256,bool,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'InterestDistributed(uint256,uint256)': TypedContractEvent<InterestDistributedEvent.InputTuple, InterestDistributedEvent.OutputTuple, InterestDistributedEvent.OutputObject>;
      InterestDistributed: TypedContractEvent<InterestDistributedEvent.InputTuple, InterestDistributedEvent.OutputTuple, InterestDistributedEvent.OutputObject>;
    

      'LoanDefaulted(uint256)': TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
      LoanDefaulted: TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
    

      'LoanOriginated(uint256,address,uint256,uint256)': TypedContractEvent<LoanOriginatedEvent.InputTuple, LoanOriginatedEvent.OutputTuple, LoanOriginatedEvent.OutputObject>;
      LoanOriginated: TypedContractEvent<LoanOriginatedEvent.InputTuple, LoanOriginatedEvent.OutputTuple, LoanOriginatedEvent.OutputObject>;
    

      'LoanRepaid(uint256,uint256)': TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
      LoanRepaid: TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Withdrawn(address,uint256,bool,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }