/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ILendingPool__factory } from './ILendingPool__factory.js';
export { ISecondaryMarket__factory } from './ISecondaryMarket__factory.js';